name: ImageDreamer-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyside6
  - transformers
  - diffusers
  - accelerate
  - invoke
  - pyinstaller
  - requests
  - pipreqs
  - pip
  - pip:
      - "xformers==0.0.24 --extra-index-url https://download.pytorch.org/whl/cu121"