name: ImageDreamer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pyside6
  - transformers
  - diffusers
  - accelerate
  - invoke
  - pip
  - appdirs
  - pip:
      - invisible-watermark