name: ImageDreamer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pyside6
  - transformers
  - diffusers
  - accelerate
  - invoke
  - pip
  - pip:
      - "xformers --extra-index-url https://download.pytorch.org/whl/cu121"